create table if not exists public.admin_users (
  id bigint generated by default as identity primary key,
  email text not null unique,
  name text not null default '',
  role text not null default 'editor' check (role in ('admin', 'editor')),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz
);

create table if not exists public.services (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  name text not null,
  eyebrow text not null default 'Support',
  category text not null default 'Consulting',
  summary text not null default '',
  description text not null default '',
  initial_price text not null default '',
  follow_up_price text not null default '',
  price_note text not null default '',
  booking_url text not null default 'https://passagewayconsulting.as.me/',
  active boolean not null default true,
  featured boolean not null default false,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz
);

create table if not exists public.events (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  title text not null,
  summary text not null default '',
  description text not null default '',
  starts_at text not null default '',
  ends_at text not null default '',
  timezone text not null default 'America/Chicago',
  format text not null default 'Online',
  registration_url text not null default 'https://passagewayconsulting.as.me/',
  image_url text not null default '',
  price_label text not null default '',
  capacity_label text not null default '',
  status text not null default 'draft' check (status in ('draft', 'published', 'cancelled')),
  featured boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz
);

create table if not exists public.blog_posts (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  title text not null,
  excerpt text not null default '',
  content text not null default '',
  cover_image_url text not null default '',
  author_name text not null default 'Passageway Consulting',
  category text not null default 'Compassion',
  seo_title text not null default '',
  seo_description text not null default '',
  status text not null default 'draft' check (status in ('draft', 'published')),
  published_at text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz
);

create table if not exists public.resources (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  title text not null,
  description text not null default '',
  category text not null default 'Guide',
  file_url text not null default '',
  image_url text not null default '',
  requires_email boolean not null default false,
  active boolean not null default true,
  featured boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz
);

create table if not exists public.testimonials (
  id bigint generated by default as identity primary key,
  quote text not null,
  name text not null default '',
  attribution text not null default 'Passageway client',
  approved boolean not null default false,
  featured boolean not null default false,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz
);

create table if not exists public.team_members (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  name text not null,
  title text not null default 'Life Consultant',
  bio text not null default '',
  credentials text not null default '',
  focus_areas text not null default '',
  image_url text not null default '',
  booking_url text not null default 'https://passagewayconsulting.as.me/',
  active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz
);

create table if not exists public.site_settings (
  key text primary key,
  value jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now(),
  updated_by text not null default ''
);

create schema if not exists private;
revoke all on schema private from public;
grant usage on schema private to anon, authenticated;

create or replace function private.is_passageway_staff(required_role text default 'editor')
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.admin_users
    where (select auth.uid()) is not null
      and lower(email) = lower(coalesce((select auth.jwt()) ->> 'email', ''))
      and active = true
      and deleted_at is null
      and (role = 'admin' or required_role = 'editor')
  );
$$;

revoke all on function private.is_passageway_staff(text) from public;
grant execute on function private.is_passageway_staff(text) to anon, authenticated;

create unique index if not exists admin_users_email_ci_idx
  on public.admin_users (lower(email));
create index if not exists services_public_list_idx
  on public.services (active, sort_order, id) where deleted_at is null;
create index if not exists events_public_list_idx
  on public.events (status, starts_at, id) where deleted_at is null;
create index if not exists blog_posts_public_list_idx
  on public.blog_posts (status, published_at desc, id desc) where deleted_at is null;
create index if not exists resources_public_list_idx
  on public.resources (active, featured desc, id desc) where deleted_at is null;
create index if not exists testimonials_public_list_idx
  on public.testimonials (approved, sort_order, id desc) where deleted_at is null;
create index if not exists team_members_public_list_idx
  on public.team_members (active, sort_order, id) where deleted_at is null;

alter table public.admin_users enable row level security;
alter table public.services enable row level security;
alter table public.events enable row level security;
alter table public.blog_posts enable row level security;
alter table public.resources enable row level security;
alter table public.testimonials enable row level security;
alter table public.team_members enable row level security;
alter table public.site_settings enable row level security;

create policy "staff can read own admin profile"
on public.admin_users for select to authenticated
using (lower(email) = lower(coalesce((select auth.jwt()) ->> 'email', '')) or private.is_passageway_staff('admin'));

create policy "admins can add admin profiles"
on public.admin_users for insert to authenticated
with check (private.is_passageway_staff('admin'));

create policy "admins can update admin profiles"
on public.admin_users for update to authenticated
using (private.is_passageway_staff('admin'))
with check (private.is_passageway_staff('admin'));

create policy "admins can delete admin profiles"
on public.admin_users for delete to authenticated
using (private.is_passageway_staff('admin'));

create policy "public can read active services"
on public.services for select
using ((active = true and deleted_at is null) or private.is_passageway_staff());

create policy "public can read published events"
on public.events for select
using ((status = 'published' and deleted_at is null) or private.is_passageway_staff());

create policy "public can read published posts"
on public.blog_posts for select
using ((status = 'published' and deleted_at is null) or private.is_passageway_staff());

create policy "public can read active resources"
on public.resources for select
using ((active = true and deleted_at is null) or private.is_passageway_staff());

create policy "public can read approved testimonials"
on public.testimonials for select
using ((approved = true and deleted_at is null) or private.is_passageway_staff());

create policy "public can read active team members"
on public.team_members for select
using ((active = true and deleted_at is null) or private.is_passageway_staff());

create policy "public can read homepage settings"
on public.site_settings for select
using (key = 'homepage' or private.is_passageway_staff());

do $$
declare
  table_name text;
begin
  foreach table_name in array array['services', 'events', 'blog_posts', 'resources', 'testimonials', 'team_members']
  loop
    execute format('create policy "staff can insert %1$s" on public.%1$I for insert to authenticated with check (private.is_passageway_staff())', table_name);
    execute format('create policy "staff can update %1$s" on public.%1$I for update to authenticated using (private.is_passageway_staff()) with check (private.is_passageway_staff())', table_name);
    execute format('create policy "staff can delete %1$s" on public.%1$I for delete to authenticated using (private.is_passageway_staff())', table_name);
  end loop;
end $$;

create policy "staff can insert site settings"
on public.site_settings for insert to authenticated
with check (private.is_passageway_staff());

create policy "staff can update site settings"
on public.site_settings for update to authenticated
using (private.is_passageway_staff())
with check (private.is_passageway_staff());

grant usage on schema public to anon, authenticated;
grant select on public.services, public.events, public.blog_posts, public.resources, public.testimonials, public.team_members, public.site_settings to anon, authenticated;
grant select, insert, update, delete on public.admin_users to authenticated;
grant insert, update, delete on public.services, public.events, public.blog_posts, public.resources, public.testimonials, public.team_members, public.site_settings to authenticated;
grant usage, select on all sequences in schema public to authenticated;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'passageway-cms',
  'passageway-cms',
  true,
  10485760,
  array['image/jpeg', 'image/png', 'image/webp', 'application/pdf']
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

create policy "public can view Passageway files"
on storage.objects for select
using (bucket_id = 'passageway-cms');

create policy "staff can upload Passageway files"
on storage.objects for insert to authenticated
with check (bucket_id = 'passageway-cms' and private.is_passageway_staff());

create policy "staff can update Passageway files"
on storage.objects for update to authenticated
using (bucket_id = 'passageway-cms' and private.is_passageway_staff())
with check (bucket_id = 'passageway-cms' and private.is_passageway_staff());

create policy "staff can delete Passageway files"
on storage.objects for delete to authenticated
using (bucket_id = 'passageway-cms' and private.is_passageway_staff());

insert into public.admin_users (email, name, role, active)
values ('isaacmosesbell@gmail.com', 'Isaac Bell', 'admin', true)
on conflict (email) do update set name = excluded.name, role = 'admin', active = true, deleted_at = null;

insert into public.services (slug, name, eyebrow, category, summary, description, initial_price, follow_up_price, price_note, booking_url, active, featured, sort_order)
values
  ('online-emotional-health-consulting', 'One-to-one consulting', 'Personal', 'Consulting', 'Personalized support to explore emotional wounds, reclaim your power, and move forward with greater resilience.', 'Personalized online support with Hannah or Kimberly, tailored to what you are walking through.', '$100', '$55', 'Initial session · Follow-up consultation', 'https://passagewayconsulting.as.me/', true, true, 1),
  ('joint-consulting', 'Kimberly + Hannah', 'Combined', 'Consulting', 'Two complementary perspectives in one supportive space, grounded in compassion, regulation, and empowerment.', 'Two complementary perspectives, one supportive space, and a shared commitment to your growth.', '$160', '$110', 'Initial session · Follow-up consultation', 'https://passagewayconsulting.as.me/', true, true, 2),
  ('online-womens-emotional-health-workshops', 'One-day workshops', 'Shared', 'Workshop', 'A brief but impactful online experience where learning, honest connection, and shared healing come together.', 'Online experiences blending education, reflection, and meaningful connection.', '', '', '', '/online-womens-emotional-health-workshops', true, false, 3),
  ('three-week-programs', 'Three-week programs', 'Transformational', 'Cohort', 'An immersive journey for women ready to grow in community, practice new tools, and make change last.', 'A longer online rhythm of learning, conversation, practice, and community.', '', '', '', '/online-womens-emotional-health-workshops#cohorts', true, false, 4)
on conflict (slug) do nothing;

insert into public.team_members (slug, name, title, bio, credentials, focus_areas, image_url, booking_url, active, sort_order)
values
  ('hannah-spacek', 'Hannah Spacek', 'Life Consultant & Naturopath', 'Hannah has worked in the wellness field for over 10 years. After overcoming chronic anxiety, people-pleasing, low self-esteem, and struggling to have a voice, she now helps women move past limiting beliefs and into self-acceptance, confidence, and freedom.', 'ND, CHC · Naturopathic Doctor · Certified Health Coach · Regenerative Detoxification Specialist', 'Dating, singleness, anxiety, self-esteem, good-girl conditioning, empowerment', '/images/hannah-spacek.webp', 'https://passagewayconsulting.as.me/', true, 1),
  ('kimberly', 'Kimberly', 'Life Consultant', 'With more than 30 years in Christian ministry and a deeply lived healing journey, Kimberly brings compassion, love, and truth to women navigating insecurity, self-hatred, religious trauma, toxic relationships, and long-standing beliefs that no longer serve them.', 'More than 30 years ministering to women', 'Trauma, self-doubt, reclaiming your voice, boundaries, peaceful authentic living', '/images/kimberly.webp', 'https://passagewayconsulting.as.me/', true, 2)
on conflict (slug) do nothing;

insert into public.resources (slug, title, description, category, file_url, image_url, requires_email, active, featured)
values ('self-compassion-reflection-guide', 'Self-Compassion Reflection Guide', 'Five gentle practices for softening self-judgment and nurturing warmth toward yourself.', 'Free guide', '/resources/self-compassion-reflection-guide.pdf', '/images/self-compassion-guide.webp', false, true, true)
on conflict (slug) do nothing;

insert into public.site_settings (key, value, updated_by)
values ('homepage', '{}'::jsonb, 'isaacmosesbell@gmail.com')
on conflict (key) do nothing;
